# Generated by Django 2.2.1 on 2019-05-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_Name', models.CharField(choices=[('Black Metal', 'Black Metal'), ('Death Metal', 'Death Metal'), ('Doom Metal', 'Doom Metal'), ('Harsh Noise Wall', 'Harsh Noise'), ('Electronic', 'Electronic'), ('Singer-Songwriter', 'Singer-Songwriter')], max_length=200)),
                ('venue', models.CharField(blank=True, max_length=200)),
                ('venue_Location', models.URLField(blank=True, default='')),
                ('Date', models.DateField(blank=True, default='')),
                ('tour_Selection', models.URLField(blank=True, default='')),
                ('owner_ID', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TEST_LIST',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
