# Generated by Django 2.2.1 on 2019-05-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0002_auto_20190522_1659'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TEST_LIST',
        ),
        migrations.RenameField(
            model_name='shows',
            old_name='Date',
            new_name='show_Date',
        ),
    ]
