# Generated by Django 2.2.1 on 2019-05-22 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0004_auto_20190522_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shows',
            name='tour_Selection',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
