# Generated by Django 2.2.1 on 2019-05-18 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allartists',
            name='choice_text',
        ),
    ]
