# Generated by Django 2.2.1 on 2019-05-18 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_remove_allartists_choice_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='artist_bc_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='artists',
            name='artist_fb_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='artists',
            name='artist_ig_username',
            field=models.CharField(default='none', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='artists',
            name='artist_spotify_url',
            field=models.URLField(default=''),
        ),
    ]
