# Generated by Django 2.2.1 on 2019-05-18 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_auto_20190518_0313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artists',
            old_name='artist_bc_url',
            new_name='artist_Bc_url',
        ),
        migrations.RenameField(
            model_name='artists',
            old_name='artist_fb_url',
            new_name='artist_Fb_url',
        ),
        migrations.RenameField(
            model_name='artists',
            old_name='artist_genre',
            new_name='artist_Genre',
        ),
        migrations.RenameField(
            model_name='artists',
            old_name='artist_ig_username',
            new_name='artist_Ig_username',
        ),
        migrations.RenameField(
            model_name='artists',
            old_name='artist_name',
            new_name='artist_Name',
        ),
        migrations.RenameField(
            model_name='artists',
            old_name='artist_spotify_url',
            new_name='artist_Spotify_url',
        ),
        migrations.RenameField(
            model_name='artists',
            old_name='signup_date',
            new_name='signup_Date',
        ),
    ]
