# Generated by Django 2.2.1 on 2019-05-18 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0004_auto_20190518_0314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artists',
            old_name='artist_Bc_url',
            new_name='artist_BC_Url',
        ),
        migrations.RenameField(
            model_name='artists',
            old_name='artist_Fb_url',
            new_name='artist_Fb_Url',
        ),
        migrations.RenameField(
            model_name='artists',
            old_name='artist_Ig_username',
            new_name='artist_Ig_Username',
        ),
        migrations.RenameField(
            model_name='artists',
            old_name='artist_Spotify_url',
            new_name='artist_Spotify_Url',
        ),
    ]
