# Generated by Django 2.2.1 on 2019-05-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0006_auto_20190518_0317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='artist_BC_URL',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artists',
            name='artist_FB_URL',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='artists',
            name='artist_Genre',
            field=models.CharField(choices=[('BM', 'Black Metal'), ('DM', 'Death Metal'), ('DO', 'Doom Metal'), ('HNW', 'Harsh Noise')], max_length=200),
        ),
        migrations.AlterField(
            model_name='artists',
            name='artist_IG_Username',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='artists',
            name='artist_Spotify_URL',
            field=models.URLField(blank=True, default=''),
        ),
    ]
