# Generated by Django 2.2.1 on 2019-05-18 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_auto_20190518_0342'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
