# Generated by Django 2.2.1 on 2019-05-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_auto_20190518_0511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='artist_Genre',
            field=models.CharField(choices=[('Black Metal', 'Black Metal'), ('Death Metal', 'Death Metal'), ('Doom Metal', 'Doom Metal'), ('Harsh Noise', 'Harsh Noise')], max_length=200),
        ),
    ]
