# Generated by Django 2.2.1 on 2019-05-18 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0011_auto_20190518_0630'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='artist_Show_Count',
            field=models.CharField(default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='artists',
            name='artist_Genre',
            field=models.CharField(choices=[('Black Metal', 'Black Metal'), ('Death Metal', 'Death Metal'), ('Doom Metal', 'Doom Metal'), ('Harsh Noise Wall', 'Harsh Noise'), ('Electronic', 'Electronic'), ('Singer-Songwriter', 'Singer-Songwriter')], max_length=200),
        ),
    ]
