# Generated by Django 2.2.1 on 2019-05-18 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_auto_20190518_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='artist_Show_Count',
            field=models.CharField(blank=True, default='0', max_length=200),
        ),
    ]
