# Generated by Django 2.2.1 on 2019-05-22 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0013_auto_20190518_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='artists',
            name='owner_ID',
            field=models.CharField(default='', max_length=200),
        ),
    ]
