# Generated by Django 2.2.1 on 2019-05-22 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0014_artists_owner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artists',
            name='owner_ID',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
