# Generated by Django 2.2.1 on 2019-05-22 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0015_auto_20190522_0335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AllArtists',
        ),
    ]
